### ISSUE TITLE
Features?

### ISSUE THREAD

**Issue by albertosouza** [albertosouza/print-tag#1]
### Features:
- [ ] Generate PDF file in pimaco formats from array of data

Whant something? Send here in comments!

**Comment by thiagoanselmo** [comment]
Vou verificar, todos os formatos e tamanhos que existe as etiquetas Pimaco e logo, posto os resultados.

**Comment by albertosouza** [comment]
Depois desenvolvo esse modulo com os testes

**Comment by thiagoanselmo** [comment]
OBS: Etiquetas abaixo para (INKJET + LASER PIMACO), abaixo está os códigos das etiquetas e os nomes para poder fazer a aquisição.

Código	Nome	Formato		Tamanho Real	

6080	6080	Retangular	25,40 X 66,70 mm	
6280	6280	Retangular	25,40 X 66,70 mm	
62580	62580	Retangular	25,40 X 66,70 mm	
6081	6081	Retangular	25,40 X 101,60 mm	
6181	6181	Retangular	25,40 X 101,60 mm	
6281	6281	Retangular	25,40 X 101,60 mm	
62581	62581	Retangular	25,40 X 101,60 mm	
6082	6082	Retangular	33,90 X 101,60 mm	
6182	6182	Retangular	33,90 X 101,60 mm	
6282	6282	Retangular	33,90 X 101,60 mm	
62582	62582	Retangular	33,90 X 101,60 mm	
6083	6083	Retangular	50,80 X 101,60 mm	
6183	6183	Retangular	50,80 X 101,60 mm	
6283	6283	Retangular	50,80 X 101,60 mm	
6184	6184	Retangular	84,70 X 101,60 mm	
6284	6284	Retangular	84,70 X 101,60 mm	
6085	6085	Retangular	279,40 X 215,90 mm	
6185	6185	Retangular	279,40 X 215,90 mm	
6285	6285	Retangular	279,40 X 215,90 mm	
6286	6286	Retangular	138,10 X 212,70 mm	
6087	6087	Retangular	12,70 X 44,40 mm	
6187	6187	Retangular	12,70 X 44,40 mm	
6287	6287	Retangular	12,70 X 44,40 mm	
6288	6288	Retangular	138,10 X 106,40 mm	
6089	6089	Retangular	16,90 X 44,40 mm	
6093	6093	Circular	27,40 X 31,0 mm	
6095	6095	Retangular	59,30 X 85,70 mm	
8296	8296	Retangular	69,80 X 69,80 mm	
8099F	8099F	Retangular	46,60 X 77,80 mm	
8099L	8099L	Retangular	16,90 X 147,60 mm	
A4248	A4248	Retangular	17,0 X 31,0 mm	
A4348	A4348	Retangular	17,0 X 31,0 mm	
A4249	A4249	Retangular	15,0 X 26,0 mm	
A4349	A4349	Retangular	15,0 X 26,0 mm	
A4250	A4250	Retangular	55,80 X 99,0 mm	
A4350	A4350	Retangular	55,80 X 99,0 mm	
A4251	A4251	Retangular	21,20 X 38,20 mm	
A4351	A4351	Retangular	21,20 X 38,20 mm	
A4254	A4254	Retangular	25,40 X 99,0 mm	
A4354	A4354	Retangular	25,40 X 99,0 mm	
A4255	A4255	Retangular	31,0 X 63,50 mm	
A4355	A4355	Retangular	31,0 X 63,50 mm	
A4256	A4256	Retangular	25,40 X 63,50 mm	
A4356	A4356	Retangular	25,40 X 63,50 mm	
A4260	A4260	Retangular	38,10 X 63,50 mm	
A4360	A4360	Retangular	38,10 X 63,50 mm	
A4261	A4261	Retangular	46,50 X 63,50 mm	
A4361	A4361	Retangular	46,50 X 63,50 mm	
A4262	A4262	Retangular	33,90 X 99,0 mm	
A4362	A4362	Retangular	33,90 X 99,0 mm	
A4263	A4263	Retangular	38,10 X 99,0 mm	
A4363	A4363	Retangular	38,10 X 99,0 mm	
A4365	A4365	Retangular	67,80 X 99,0 mm	
A4267	A4267	Retangular	288,50 X 200 mm	
A4367	A4367	Retangular	288,50 X 200 mm	
A4368	A4368	Retangular	143,40 X 199,90 mm	
6180	6180	Retangular	25,40 X 66,70 mm	
A4375	A4375	Retangular	33,0 X 105,0 mm	
A4370	A4370	Retangular	33,0 X 70 mm	


Vou pegar todos modelos de etiquetas que a Pimaco trabalha, ai depois podemos juntos trabalhar no código.

**Comment by thiagoanselmo** [comment]
```

OBS: Etiquetas abaixo para (INKJET + LASER PIMACO), abaixo está 
os códigos das etiquetas e os nomes para poder fazer a aquisição. 
Esses são os modelos mais utilizados, vou pegar todos os modelos e portar aqui, e 
depois vamos para os códigos juntos.

Código		Nome		Formato			Tamanho Real	

6080		6080		Retangular		25,40 X 66,70 mm	
6280		6280		Retangular		25,40 X 66,70 mm	
62580		62580		Retangular		25,40 X 66,70 mm	
6081		6081		Retangular		25,40 X 101,60 mm	
6181		6181		Retangular		25,40 X 101,60 mm	
6281		6281		Retangular		25,40 X 101,60 mm	
62581		62581		Retangular		25,40 X 101,60 mm	
6082		6082		Retangular		33,90 X 101,60 mm	
6182		6182		Retangular		33,90 X 101,60 mm	
6282		6282		Retangular		33,90 X 101,60 mm	
62582		62582		Retangular		33,90 X 101,60 mm	
6083		6083		Retangular		50,80 X 101,60 mm	
6183		6183		Retangular		50,80 X 101,60 mm	
6283		6283		Retangular		50,80 X 101,60 mm	
6184		6184		Retangular		84,70 X 101,60 mm	
6284		6284		Retangular		84,70 X 101,60 mm	
6085		6085		Retangular		279,40 X 215,90 mm	
6185		6185		Retangular		279,40 X 215,90 mm	
6285		6285		Retangular		279,40 X 215,90 mm	
6286		6286		Retangular		138,10 X 212,70 mm	
6087		6087		Retangular		12,70 X 44,40 mm	
6187		6187		Retangular		12,70 X 44,40 mm	
6287		6287		Retangular		12,70 X 44,40 mm	
6288		6288		Retangular		138,10 X 106,40 mm	
6089		6089		Retangular		16,90 X 44,40 mm	
6093		6093		Circular		27,40 X 31,0 mm	
6095		6095		Retangular		59,30 X 85,70 mm	
8296		8296		Retangular		69,80 X 69,80 mm	
8099F		8099F		Retangular		46,60 X 77,80 mm	
8099L		8099L		Retangular		16,90 X 147,60 mm	
A4248		A4248		Retangular		17,0 X 31,0 mm	
A4348		A4348		Retangular		17,0 X 31,0 mm	
A4249		A4249		Retangular		15,0 X 26,0 mm	
A4349		A4349		Retangular		15,0 X 26,0 mm	
A4250		A4250		Retangular		55,80 X 99,0 mm	
A4350		A4350		Retangular		55,80 X 99,0 mm	
A4251		A4251		Retangular		21,20 X 38,20 mm	
A4351		A4351		Retangular		21,20 X 38,20 mm	
A4254		A4254		Retangular		25,40 X 99,0 mm	
A4354		A4354		Retangular		25,40 X 99,0 mm	
A4255		A4255		Retangular		31,0 X 63,50 mm	
A4355		A4355		Retangular		31,0 X 63,50 mm	
A4256		A4256		Retangular		25,40 X 63,50 mm	
A4356		A4356		Retangular		25,40 X 63,50 mm	
A4260		A4260		Retangular		38,10 X 63,50 mm	
A4360		A4360		Retangular		38,10 X 63,50 mm	
A4261		A4261		Retangular		46,50 X 63,50 mm	
A4361		A4361		Retangular		46,50 X 63,50 mm	
A4262		A4262		Retangular		33,90 X 99,0 mm	
A4362		A4362		Retangular		33,90 X 99,0 mm	
A4263		A4263		Retangular		38,10 X 99,0 mm	
A4363		A4363		Retangular		38,10 X 99,0 mm	
A4365		A4365		Retangular		67,80 X 99,0 mm	
A4267		A4267		Retangular		288,50 X 200 mm	
A4367		A4367		Retangular		288,50 X 200 mm	
A4368		A4368		Retangular		143,40 X 199,90 mm	
6180		6180		Retangular		25,40 X 66,70 mm	
A4375		A4375		Retangular		33,0 X 105,0 mm	
A4370		A4370		Retangular		33,0 X 70 mm	

```

**Comment by albertosouza** [comment]
Bastante coisa, para iniciar podemos escolher umas 5.

**Comment by thiagoanselmo** [comment]
Claro é sim, vou ver dentre elas as 5 mais utilizadas e começamos, mais fiz isso já pra deixar como registro, caso alguém venha procurar possa ajudar.

**Comment by albertosouza** [comment]
@thiagoanselmo o que vamos imprimir em cada etiquetas?
Apenas um texto como o nome das pessoas?

**Comment by thiagoanselmo** [comment]
@albertosouza gostaria de fazer impressão de código de barras, eu gerei um PDF com QRCode para testes, mais o problema é, se for um 'texto' um pouco extenso fica muito ruim de o leitor fazer o reconhecimento nas etiquetas da Pimaco, pois as impressoras a laser não fazem uma boa resolução para QRCode, agora já para códigos de barra é melhor utilizando etiquetas Pimaco, agora se for imprimir QRCode nas impressoras Zebras ai sim tem uma boa qualidade, hoje passo os 5 modelos de etiquetas Pimaco, para começarmos os trabalhos. Estive um pouco atarefado e acabei não conseguindo.

**Comment by thiagoanselmo** [comment]
@albertosouza me passa teu skype, ou me adiciona para trocamos uma idéia mais rápido, já tenho aqui em mãos as etiquetas que vamos fazer, momento que já vou postar.

**Comment by thiagoanselmo** [comment]
Para finalidade de registro, estou enviando todas as informações dos modelos das etiquetas (tamanho, quantidade por folha, margem).

![tamanhos inkjet laser i](https://cloud.githubusercontent.com/assets/12956934/15150386/5527b0b8-16a3-11e6-93c7-f627b3728bf5.PNG)
![tamanhos inkjet laser ii](https://cloud.githubusercontent.com/assets/12956934/15150387/554d765e-16a3-11e6-8693-62ad9e1c2cc9.PNG)

**Comment by albertosouza** [comment]
done for first api version
