### ISSUE TITLE
Erro 'done is not defined'

### ISSUE THREAD

**Issue by luiza-avelino** [albertosouza/print-tag#10]
Quanto rodo a aplicação recebo o erro abaixo:
"Uncaught ReferenceError: done is not defined"
    at PDFDocument.<anonymous> (app.js:94)
    at PDFDocument.emit (events.js:199)
    at endReadableNT (_stream_readable.js:1141)
    at processTicksAndRejections (internal/process/task_queues.js:81)

Como paliativo coloquei um return vazio mas o meu documento não está sendo criado.

**Comment by albertosouza** [comment]
Oi Luiza, o `done` só está disponível na função **onSetOneTag*
Preciso de mais informações para ajudar mais...

**Comment by luiza-avelino** [comment]
Alberto estou com uma aplicação electron que lê um arquivo .CSV, extrai as informações e uso sua biblioteca para gerar as etiquetas. Cada linha do meu arquivo é uma etiqueta:

**Comment by albertosouza** [comment]
@luiza-avelino 
No seu código o done não existe na parte:
```
pt.doc.on("end", function() {
done(); // <-- esse done não está definido no seu código e não faz parte do print tag
});
```

**Comment by luiza-avelino** [comment]
Entendi, achei que o done() era parte da funcionalidade do print tag. Após todas as etiquetas estarem pronta o que me recomenda a fazer para encerrar o arquivo? Porque já tentei algumas maneiras e o arquivo acaba encerrando antes de todas as etiquetas estarem prontas e o arquivo acaba sendo gerado corrompido.
