### ISSUE TITLE
Usage proposal

### ISSUE THREAD

**Issue by albertosouza** [albertosouza/print-tag#3]
First usage proposal work with streams for better support to generate big PDF files

Lets print one list of data in pimaco id 62580 format: Retangular - 25,40 X 66,70 mm    

```js
var data = [
  {
    text: 'Super man'
  },
  {
    text: 'Batman'
  },
  {
    text: 'Dead Poll'
  }    
];

var printTicket = require('print-ticket', data); 

// Usage 1- return one stream
var job = printTicket.JSONToPDF('pimaco_62580', data);
job.on('chuck', function(data) {
 // ...
});
job.on('error', function(err) {
  // something did wrong
});
job.on('end', function() {
 // done all
});

// Usage 2- generate and automaticaly pipe to response
printTicket.JSONToPDF('pimaco_62580', data, res);
```

**Comment by albertosouza** [comment]
@thiagoanselmo you can git an opinion here?

**Comment by albertosouza** [comment]
```js

var result = print('pimaco_62580', 10, function(i, x, y, PDFkit){

// print with x and y coords
// do nothing for skiip
});

result.pipe(res);

```

**Comment by thiagoanselmo** [comment]
Fiz esse final de semana o esqueleto da etiqueta Pimaco 6187 pois preciso finalizar esse modulo de etiquetas no meu sistema do INMETRO aqui da empresa, falta validar com texto e código de barra, vou ver se mato isso hoje ainda. E posto os códigos. 

![pimaco 6187](https://cloud.githubusercontent.com/assets/12956934/15277128/099fe840-1ad1-11e6-9631-2cd072f8d8b7.jpg)
[Teste pimaco 6187.pdf](https://github.com/albertosouza/print-ticket/files/265302/Teste.pimaco.6187.pdf)

**Comment by albertosouza** [comment]
Show!

**Comment by albertosouza** [comment]
done and README.md updated
