### ISSUE TITLE
Tags on top of others

### ISSUE THREAD

**Issue by alejrdroid** [albertosouza/print-tag#7]
Hi! When  new page is added the first tag gets on top of other, like this first tag on the second page
![captura de tela de 2018-07-11 00-43-38](https://user-images.githubusercontent.com/7718454/42549627-85e1dd76-84a3-11e8-95bc-2348b4b27264.png)

To avoid that I just skipped the first `doc.addPage` at `PrintTicket.prototype.nextTag` on index.js , and then no more tags on top of the others
```
// calc next page
  this.currentTag++;
  if (this.currentTag >= this.format.maxTagsInPage) {
    //skip the first page
    if(this.page <= 1){
      this.page++;
    }
    else{
      this.page++;
      this.currentTag = 0;

      this.doc.addPage({
        size: this.format.paperSize,
        margins: this.format.paperMargins
      });
    }
  }
```

**Comment by albertosouza** [comment]
@alejrdroid thanks for your feedback.
fix applied and new version published in NPM.
